#!/usr/bin/python3
import os
os.system("clear")
print("—" * 50)
print("W3lc0m3 T0 Bitc73s P01ic3 .....")
print("—" * 50)
#Define The Main Menu
def menu():
	while True:
		print("""
1-Show Team Members
2-Show Team Targets
3-Install The Requierment Tools
4-Exit
[@]Contact Me On 
 | Instagram : cproo1 |		
		""")
		selection = input("[$] Select a Number: ")
		if selection == "1":
			os.system("cat members.txt")
		elif selection == "2":
			os.system("cat Targets")
		elif selection == "3":
			os.system("clear")
			os.system("./install")
menu()